In [ ]:
# Data Inconsistency

# 1 inconsistent formats(e.g., date formats) ✅
# 2 inconsistent Naming Conventions(e.g., "NY" vs "New York") ✅
# 3 Typographical Errors(e.g., "Calfornia" instead of "California") ✅
# 4 Duplicate Entries(e.g., same record entered multiple times) ✅
# 5 contradictory Data(e.g., age 25 with birth year 1990)

In [2]:
# Libraries 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [17]:
# we will create a sample dataframe with some inconsistencies



data = {
    'date': ['2020-1-01', '01/march/2020', '2020-03-01', '2020-04-01', '05-01-2020', '2020/06/01', '2020-07-01'],
    'Country': ['USA', 'U.S.A', 'Canada', 'Canada', 'America', 'Canada', 'USA'],
    'Name': ['John', 'john', 'jhon', 'john', 'jhon', 'john', 'john'],
    'Sales_2020': [100, 150, 200, 250, None, 350, 400],
    'Sales_2021': [110, None, 210, 260, 310, 360, 410] 
}
df = pd.DataFrame(data)
df.head()

            date  Country  Name  Sales_2020  Sales_2021
0      2020-1-01      USA  John       100.0       110.0
1  01/march/2020    U.S.A  john       150.0         NaN
2     2020-03-01   Canada  jhon       200.0       210.0
3     2020-04-01   Canada  john       250.0       260.0
4     05-01-2020  America  jhon         NaN       310.0

In [ ]:
# 01 Standardizing Date Formats ✅


# i want data in year-month-day format
# i use dateparser library to parse different date formats
# dateparser is more flexible than pandas to parse dates

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)


import dateparser

def clean_date(x):
    if pd.isna(x):
        return None
    x = str(x).strip()
    result = dateparser.parse(x)
    return result

df['date'] = df['date'].apply(clean_date)
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')


df.head()

         date  Country  Name  Sales_2020  Sales_2021
0  2020-11-01      USA  John       100.0       110.0
1  2020-03-01    U.S.A  john       150.0         NaN
2  2020-03-01   Canada  john       200.0       210.0
3  2020-04-01   Canada  john       250.0       260.0
4  2020-05-01  America  john         NaN       310.0

In [18]:
# 2 inconsistent Naming Conventions(e.g., "NY" vs "New York") ✅
# we use mapping to standardize country names


country_mapping = {
'USA': 'United States','U.S.A': 'United States','America': 'United States'}
df['Country'] = df['Country'].replace(country_mapping)
df.head()

            date        Country  Name  Sales_2020  Sales_2021
0      2020-1-01  United States  John       100.0       110.0
1  01/march/2020  United States  john       150.0         NaN
2     2020-03-01         Canada  jhon       200.0       210.0
3     2020-04-01         Canada  john       250.0       260.0
4     05-01-2020  United States  jhon         NaN       310.0

In [ ]:
# 3 Typographical Errors(e.g., "Calfornia" instead of "California") ✅
# we use replace method to fix typos

df['Name']= df['Name'].replace({'jhon':'john'})
df.head()

            date        Country  Name  Sales_2020  Sales_2021
0      2020-1-01  United States  John       100.0       110.0
1  01/march/2020  United States  john       150.0         NaN
2     2020-03-01         Canada  john       200.0       210.0
3     2020-04-01         Canada  john       250.0       260.0
4     05-01-2020  United States  john         NaN       310.0