In [1]:
# Data Merge or Integration ✅

# Data Concatenation

In [2]:
# import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Data Merging

# Now we create two sample datasets to demonstrate data merging

data1 = {
    'ID': [1, 2, 3, 4], 
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40]
}


data2 = {
    'ID': [1, 2, 3, 4],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
    'salary': [70000, 80000, 90000, 100000]
}


df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df1.head()

   ID     Name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

In [4]:
#Now we will merge these two datasets based on the 'ID' column
merged = pd.merge(df1,df2,on='ID',how='inner')
merged.head()

   ID     Name  age         city  salary
0   1    Alice   25     New York   70000
1   2      Bob   30  Los Angeles   80000
2   3  Charlie   35      Chicago   90000
3   4    David   40      Houston  100000

In [5]:
# Data Concatenation
# Data Concatenation is the process of combining two or more datasets along a particular axis (rows or columns). This is useful when you have datasets with the same structure and want to combine them into a single dataset.

# Now we create three sample datasets to demonstrate data concatenation


data1 = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
data2 = {'Name': ['Charlie', 'David'], 'Age': [35, 40]}
data3 = {'City': ['New York', 'Los Angeles'], 'Salary': [70000, 80000]}


df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
df1.head()

    Name  Age
0  Alice   25
1    Bob   30

In [20]:
# Now we will concatenate these datasets along columns

concatenated_columns = pd.concat([df1,df2],axis=1,)
concatenated_columns.head()

    Name  Age     Name  Age
0  Alice   25  Charlie   35
1    Bob   30    David   40

In [ ]:
# Concatenate datasets along rows
concatenated_rows = pd.concat([df1,df2],axis=0)
concatenated_rows.head()

      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1    David   40